FROM python:3.10-slim

# Instala as dependências de sistema essenciais para o funcionamento do Qt6/X11
RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libgl1 \
    libegl1 \
    libfontconfig1 \
    libxrender1 \
    libx11-6 \
    libxcb-xinerama0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-shape0 \
    libxcb-xfixes0 \
    libxcb-cursor0 \
    libxkbcommon-x11-0 \
    libdbus-1-3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN pip install --no-cache-dir PyQt6

COPY src/client/ ./src/client/
CMD ["python", "src/client/mainCliente.py"]